FROM python:3.10-slim

WORKDIR /app

# Install kuksa-client
RUN pip install --no-cache-dir kuksa-client==0.5.1a1

# Copy fixture runner script
COPY fixture-runner/fixture_runner.py /app/

CMD ["python", "/app/fixture_runner.py"]
