version: '3.8'

services:
  # KUKSA Databroker
  databroker:
    image: ghcr.io/eclipse-kuksa/kuksa-databroker:0.6.0
    ports:
      - "55556:55555"
    volumes:
      - ${VSS_FILE:-../test-data/vss_full.json}:/data/vss.json:ro
    command: --insecure --vss /data/vss.json

  # Test Framework v4
  test-runner:
    build: .
    depends_on:
      - databroker
    environment:
      - KUKSA_URL=databroker:55555
      - PYTHONUNBUFFERED=1
    volumes:
      - ./examples:/app/examples
      - ./results:/app/results
    working_dir: /app