version: '3.8'

services:
  # KUKSA Databroker
  databroker:
    image: ghcr.io/eclipse/kuksa.val/databroker:0.6.0
    ports:
      - "55556:55555"
    command: --insecure

  # Test Framework v4
  test-runner:
    build: .
    depends_on:
      - databroker
    environment:
      - KUKSA_URL=databroker:55555
    volumes:
      - ./examples:/app/examples
      - ./results:/app/results
      - /var/run/docker.sock:/var/run/docker.sock  # For container log access
    command: >
      python -m kuksa_test.cli
      /app/examples/climate_control_test.yaml
      --kuksa-url databroker:55555
      --format console
      
  # Example Climate Control Application
  climate-control:
    build:
      context: ../examples
      dockerfile: Dockerfile.climate
    depends_on:
      - databroker
    environment:
      - KUKSA_URL=databroker:55555
    command: /app/climate_control